security:
  - https://aws.amazon.com/security/security-bulletins/rss/feed/
  - https://cloudblog.withgoogle.com/topics/threat-intelligence/rss/
  - https://techcrunch.com/category/security/feed/
  - https://alas.aws.amazon.com/alas.rss
  - https://www.cyber.gov.au/rss/alerts
  - https://krebsonsecurity.com/feed/
  - https://feeds.feedburner.com/TheHackersNews
  - https://www.itnews.com.au/RSS/rss.ashx?type=Category&ID=32
  - https://www.tenable.com/blog/cyber-exposure-alerts/feed
  - https://www.securityweek.com/feed/
  - https://www.bleepingcomputer.com/feed/
  - https://www.darkreading.com/rss.xml
  - https://therecord.media/feed/
  - https://blog.malwarebytes.com/feed/
  - https://msrc.microsoft.com/blog/feed/
  - https://unit42.paloaltonetworks.com/feed/
  - https://www.cisa.gov/uscert/ncas/alerts.xml
  - https://www.ncsc.gov.uk/api/1/services/v1/report-rss-feed.xml
  - https://redcanary.com/feed/
  - https://securityboulevard.com/feed/
  #- https://isc.sans.edu/rssfeed.xml
  #- https://www.nist.gov/news-events/cybersecurity/rss.xml
  #- https://azurecomcdn.azureedge.net/en-us/updates/feed/?query=security
# massyn:
#   - https://massyn.net/rss.xml