security:
  - https://aws.amazon.com/security/security-bulletins/rss/feed/
  - https://cloudblog.withgoogle.com/topics/threat-intelligence/rss/
  - https://techcrunch.com/category/security/feed/
  - https://alas.aws.amazon.com/alas.rss
  - https://www.cyber.gov.au/rss/alerts
  - https://krebsonsecurity.com/feed/
  - https://feeds.feedburner.com/TheHackersNews
  - https://www.itnews.com.au/RSS/rss.ashx?type=Category&ID=32
  - https://www.tenable.com/blog/cyber-exposure-alerts/feed
  - https://www.securityweek.com/feed/
  #- https://www.nist.gov/news-events/cybersecurity/rss.xml
  #- https://azurecomcdn.azureedge.net/en-us/updates/feed/?query=security
massyn:
  - https://massyn.net/rss.xml