mastodon:
  endpoint: https://infosec.exchange
rss:
  - https://aws.amazon.com/security/security-bulletins/rss/feed/
  - https://techcrunch.com/category/security/feed/
  - https://alas.aws.amazon.com/alas.rss
  - https://www.cyber.gov.au/rss/alerts
  - https://www.nist.gov/news-events/cybersecurity/rss.xml
