name: Python application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
  - cron: '0 0,3,6,9,12,15,18,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      security_ACCESS_TOKEN: ${{ secrets.SECURITY_ACCESS_TOKEN }}
      security_ENDPOINT: https://infosec.exchange
      massyn_ACCESS_TOKEN: ${{ secrets.MASSYN_ACCESS_TOKEN }}
      massyn_ENDPOINT: https://aus.social
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3
      uses: actions/setup-python@v3
#     with:
#        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Publish
      run: |
        python rss-reader.py
    
