name: Python application
on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:
  schedule:
  - cron: '0 */4 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      security_ACCESS_TOKEN: ${{ secrets.SECURITY_ACCESS_TOKEN }}
      security_ENDPOINT: https://infosec.exchange
      massyn_ACCESS_TOKEN: ${{ secrets.MASSYN_ACCESS_TOKEN }}
      massyn_ENDPOINT: https://aus.social
      HOSTCHECK: ${{ secrets.HOSTCHECK }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3
      uses: actions/setup-python@v3
#     with:
#        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Publish
      run: |
        python rss-reader.py && curl -fsS -m 10 --retry 5 -o /dev/null $HOSTCHECK
  notify-on-failure:
    if: failure()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Failure Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "🚨 *Build Failed!* ❌\n*Repo:* ${{ github.repository }}\n*Branch:* ${{ github.ref }}\n*Commit:* ${{ github.sha }}"
          SLACK_COLOR: "#FF0000"
    
