name: Python application
on:
  schedule:
  - cron: '0 0,3,6,9,12,15,18,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
      MASTODON_ENDPOINT: ${{ secrets.MASTODON_ENDPOINT }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Publish
      run: |
        python rss-reader.py
    
